# Generated by Django 6.1 on 2026-09-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_notification', models.BooleanField(default=False, help_text='True if notification is intended for admin dashboard')),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS', 'Order Status Change'), ('NEW_ORDER', 'New Order Received'), ('LOW_STOCK', 'Low Stock Warning'), ('OUT_OF_STOCK', 'Out of Stock Alert'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
