# Generated by Django 6.1 on 2026-09-18 05:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(blank=True, choices=[(80, '80 GSM'), (90, '90 GSM'), (100, '100 GSM'), (120, '120 GSM'), (140, '140 GSM')], help_text='Selected GSM for Raw Material products', null=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'db_table': 'store_cartitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order reference', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Out for Delivery'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_name', models.CharField(help_text='Snapshot customer name at purchase', max_length=150)),
                ('customer_mobile', models.CharField(help_text='Snapshot mobile number at purchase', max_length=20)),
                ('customer_address', models.TextField(help_text='Snapshot delivery address at purchase')),
                ('is_removed_by_admin', models.BooleanField(default=False, help_text='Hides order from active Admin order management list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(blank=True, choices=[(80, '80 GSM'), (90, '90 GSM'), (100, '100 GSM'), (120, '120 GSM'), (140, '140 GSM')], help_text='Snapshot GSM for Raw Material products', null=True)),
                ('product_name', models.CharField(help_text='Snapshot product name', max_length=255)),
                ('size', models.CharField(blank=True, help_text='Snapshot product size', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot weight in kg for Raw Material products', max_digits=10, null=True)),
                ('gsm_price_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot GSM price per kg at order time', max_digits=10, null=True)),
                ('variant_name', models.CharField(blank=True, help_text='Snapshot variant/quality/GSM name', max_length=150)),
                ('unit_packing', models.CharField(blank=True, help_text='Snapshot packing unit', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price at purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'db_table': 'store_orderitem',
            },
        ),
    ]
