# Generated by Django 6.1 on 2026-09-18 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGSMPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(choices=[(80, '80 GSM'), (90, '90 GSM'), (100, '100 GSM'), (120, '120 GSM'), (140, '140 GSM')], help_text='GSM paper weight specification', unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Central global price for this GSM specification', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store_globalgsmprice',
                'ordering': ['gsm'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, help_text="Size dimension e.g. '36 × 48 inch', '8 inch'", max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg for Raw Material products', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Weight must be greater than 0 kg.')])),
                ('gsm', models.IntegerField(blank=True, choices=[(80, '80 GSM'), (90, '90 GSM'), (100, '100 GSM'), (120, '120 GSM'), (140, '140 GSM')], help_text='Selected GSM specification for Raw Material product', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'db_table': 'store_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text="e.g. 'Silver Premium - 100 Pcs/Bori' or '50kg Kraft Reel'", max_length=100)),
                ('unit_packing', models.CharField(blank=True, help_text="e.g. '100 pcs/bori', '200 pcs/bag', '50 kg reel'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, help_text='Available stock quantity in bori/bags/reels', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'store_productvariant',
                'ordering': ['product', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ProductGSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(choices=[(80, '80 GSM'), (90, '90 GSM'), (100, '100 GSM'), (120, '120 GSM'), (140, '140 GSM')], help_text='Supported GSM paper weight choice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gsms', to='products.product')),
            ],
            options={
                'db_table': 'store_productgsm',
                'ordering': ['product', 'gsm'],
                'unique_together': {('product', 'gsm')},
            },
        ),
    ]
