# Generated by Django 6.1 on 2026-09-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category_type', models.CharField(choices=[('DISPOSABLE', 'Disposable Products'), ('RAW_MATERIAL', 'Raw Materials')], default='DISPOSABLE', help_text='Distinguishes finished disposable products from industrial raw materials', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'store_category',
                'ordering': ['category_type', 'name'],
            },
        ),
    ]
