# Generated by Django 6.1 on 2026-09-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.IntegerField(default=0)),
                ('change_amount', models.IntegerField(help_text='Stock quantity added (+) or subtracted (-)')),
                ('new_stock', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('NEW_STOCK', 'New Factory Stock Added'), ('ORDER_DEDUCTION', 'Order Deduction'), ('ORDER_CANCELLATION', 'Order Cancellation Restoration')], default='MANUAL_ADJUSTMENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User executing stock update', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.productvariant')),
            ],
            options={
                'db_table': 'store_stockhistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
